### PR TITLE
Create Javadoc documentation for testing branches

### PR DESCRIPTION
**Pull request by MatthewL246**
This updates the Javadoc generation action.

I am not sure if it is ready to be merged yet, what do you think @tom-ricci?
By the way, I simplified the file in my most recent commit to use more environment variables.

### CODE REVIEW

**Comment by MatthewL246** [comment]
I will test this on my fork to see if it has the expected results. Edit: There are a couple problems that need to be fixed, do not merge yet.

**Comment by MatthewL246** [comment]
Okay, all of the issues have been fixed. The only remaining "issue" is that the javadoc and reports folders need to be deleted and recreated on the `gh-pages` branch. I think this is ready to merge @tom-ricci.

**Comment by tom-ricci** [comment]
Alright, I'll fix that and merge later tonight!

**Comment by tom-ricci** [comment]
Alright, that should be it. I'll merge when checks finish.

**Pull request merged**
