### PR TITLE
Build the APK web installer here

### PR DESCRIPTION
**Pull request by MatthewL246**
**Changes:**

We should have never used automated commits to commit build results to this repo. It's just a terrible way to do things.

**Reviewers:**

@XaverianTeamRobotics/senior-programmers

### CODE REVIEW

**Review by michaell4438 — APPROVED** [review]
lgtm

**Comment by MatthewL246** [comment]
Some stuff needs to be fixed in webinstaller first before merging.

**Comment by michaell4438** [comment]
alright

**Comment by michaell4438** [comment]
Just merge when you are ready

**Comment by MatthewL246** [comment]
Yeah, this isn't a perfect solution, but I'm going to do some more work on updating the docs build process XaverianTeamRobotics/docs#18.

**Pull request merged**
