### PR TITLE
Test pull request for Thomas-Ricci => master

### PR DESCRIPTION
**Pull request by MatthewL246**
Okay, so how many merge conflicts will need to be resolved before this code is merged into master?

### CODE REVIEW

**Comment by MatthewL246** [comment]
Fortunately, it looks like the only real conflict is the readme.
Also, the build is failing. Do you know that is up with that @tom-ricci?

**Comment by MatthewL246** [comment]
Looks like the error is:
```java
warning: Supported source version 'RELEASE_7' from annotation processor 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' less than -source '8'
/home/runner/work/FtcRobotController/FtcRobotController/TeamCode/src/main/java/org/firstinspires/ftc/teamcode/main/autonomous/image/InitialDetection_old.java:137: error: cannot find symbol
        parameters.cameraName = hardwareMap.get(WebcamName.class, hardwareMap.appContext.getString(R.string.Webcam1));
                                                                                                           ^
  symbol:   variable Webcam1
  location: class string
```
I guess this is a CI problem because the builds work locally. Guess I'm going to have to fix that, yikes.
Or I could just delete/comment out `TeamCode/src/main/java/org/firstinspires/ftc/teamcode/main/autonomous/image/InitialDetection_old.java`, since it looks like it is just some old/legacy code.

**Comment by MatthewL246** [comment]
I will experiment more later.

**Comment by tom-ricci** [comment]
@michaell4438 did everything in main.autonomous (as of the last commit of this pr), I don't know whether commenting that out is fine or not

**Pull request closed without merging**
