### PR TITLE
Create a workflow for generating documentation with Javadoc

### PR DESCRIPTION
**Pull request by MatthewL246**
This action builds the project and uses Javadoc to generate documentation for the project if the build succeeds.
Adding the Javadoc output to the `gh-pages` branch is currently not implemented but is planned.
Note that this action only runs when code is pushed to the `master` branch to reduce the number of commits that will be made to the `gh-pages` branch, but this action can also be run manually.
Unfortunately, the only way that I could find to get Javadoc to work requires a hack that involves using a command-line switch to ignore errors.

I believe that the workflow is now finished.

My plans:

- [x] Commit the Javadoc output to the `gh-pages` branch.
- [x] Upload the build lint results to the `gh-pages` branch.
- [x] Find a way of running Javadoc without the `-Xdoclint:none --ignore-source-errors` hack. [Apparently not possible]
- [x] Prepare the `gh-pages` branch for the action's first run.

### CODE REVIEW

**Comment by tom-ricci** [comment]
So far this looks good, I'll check it more in-depth tomorrow!

**Comment by MatthewL246** [comment]
More features are on the way. 😀

**Comment by MatthewL246** [comment]
Okay, I believe that the workflow file is now done. I will merge this soon and then prepare the `gh-pages` branch.

**Comment by MatthewL246** [comment]
Merged, and it works! [CLICK HERE](https://xaverianteamrobotics.github.io/FtcRobotController/javadoc)

**Comment by tom-ricci** [comment]
🎉

**Pull request merged**
