### PR TITLE
Did Someone Say Airplanes?  I'm Michael Lachut and I fly airplanes.  …

### LINKED ISSUE #574: Airplane launcher code

### PR DESCRIPTION
**Pull request by marco28p**
…Vrrrrreeewwwwwww  **Explosion Sound**

By the way, this runs the airplane lancher.

**Changes:**

(put what you changed here)

**Controls and Usage:**

(put how to use your code here)

**Reviewers:**

@XaverianTeamRobotics/senior-programmers

### CODE REVIEW

**Review by MatthewL246 — CHANGES_REQUESTED** [review]
Please move this code into a new feature (with a test opmode) before merging it into master. If you need help with that, Michael or I can help. (Same as #582)

**Comment by michaell4438** [comment]
Also please name the feature something descriptive

**Comment by MatthewL246** [comment]
@michaell4438 Should this replace the [AirplaneLauncher feature](https://github.com/XaverianTeamRobotics/FtcRobotController/blob/644e1a194f47b6f037c12efcfdb6583402317631/TeamCode/src/main/java/org/firstinspires/ftc/teamcode/features/AirplaneLauncher.java)?

**Comment by michaell4438** [comment]
Yeah probably

**Comment by michaell4438** [comment]
OpMode not required anymore

**Review by MatthewL246 — COMMENTED** [review]
‍

**Pull request closed without merging**
