### PR TITLE
Update my branch with michael's new code

### PR DESCRIPTION
**Pull request by tom-ricci**

### CODE REVIEW

**Comment by MatthewL246** [comment]
Huh. Now the build succeeds, but the Javadoc generation borked itself. Weird. *Also, I have absolutely no idea how to fix it.*

**Comment by tom-ricci** [comment]
That makes sense. *I also have no idea how to fix it.*

We could possibly try emulating Android Studio and building javadocs through it inside an action, athough I don't know how hard that would be. It would be possible though.

**Comment by MatthewL246** [comment]
Well, the error is
```java
Generating javadoc-output/org/firstinspires/ftc/teamcode/main/utils/devices/package-tree.html...
javadoc: error - An internal exception has occurred. 
	(java.lang.NullPointerException: Cannot invoke "com.sun.tools.javac.code.Type.isPrimitive()" because "t" is null)
Please file a bug against the javadoc tool via the Java bug reporting page
(http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com)
for duplicates. Include error messages and the following diagnostic in your report. Thank you.
java.lang.NullPointerException: Cannot invoke "com.sun.tools.javac.code.Type.isPrimitive()" because "t" is null
	at jdk.compiler/com.sun.tools.javac.code.Types.erasure(Types.java:2388)
	at jdk.compiler/com.sun.tools.javac.code.Types$14.visitTypeVar(Types.java:2446)
	at jdk.compiler/com.sun.tools.javac.code.Types$14.visitTypeVar(Types.java:2396)
	at jdk.compiler/com.sun.tools.javac.code.Type$TypeVar.accept(Type.java:1685)
	at jdk.compiler/com.sun.tools.javac.code.Types$DefaultTypeVisitor.visit(Types.java:4902)
	at jdk.compiler/com.sun.tools.javac.code.Types.erasure(Types.java:2391)
	at jdk.compiler/com.sun.tools.javac.code.Types.erasure(Types.java:2377)
	at jdk.compiler/com.sun.tools.javac.model.JavacTypes.erasure(JavacTypes.java:134)
	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.util.Utils$5.visitTypeVariable(Utils.java:1233)
	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.util.Utils$5.visitTypeVariable(Utils.java:1212)
	at jdk.compiler/com.sun.tools.javac.code.Type$TypeVar.accept(Type.java:1721)
	at java.compiler@16.0.2/javax.lang.model.util.AbstractTypeVisitor6.visit(AbstractTypeVisitor6.java:108)
	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.util.Utils.asTypeElement(Utils.java:1250)
	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.LinkInfoImpl.setContext(LinkInfoImpl.java:405)
	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.LinkInfoImpl.<init>(LinkInfoImpl.java:287)
	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.LinkFactoryImpl.getTypeParameterLink(LinkFactoryImpl.java:174)
	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.LinkFactoryImpl.getTypeParameterLinks(LinkFactoryImpl.java:157)
	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.util.links.LinkFactory.getLink(LinkFactory.java:195)
	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.HtmlDocletWriter.getLink(HtmlDocletWriter.java:722)
	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.HtmlDocletWriter.addPreQualifiedClassLink(HtmlDocletWriter.java:857)
2 errors
	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.HtmlDocletWriter.addPreQualifiedStrongClassLink(HtmlDocletWriter.java:891)
	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.AbstractTreeWriter.addPartialInfo(AbstractTreeWriter.java:174)
	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.AbstractTreeWriter.addLevelInfo(AbstractTreeWriter.java:89)
	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.AbstractTreeWriter.addLevelInfo(AbstractTreeWriter.java:91)
	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.AbstractTreeWriter.addTree(AbstractTreeWriter.java:120)
	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.AbstractTreeWriter.addTree(AbstractTreeWriter.java:109)
	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.PackageTreeWriter.generatePackageTreeFile(PackageTreeWriter.java:108)
	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.PackageTreeWriter.generate(PackageTreeWriter.java:89)
	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.HtmlDoclet.generatePackageFiles(HtmlDoclet.java:345)
	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.AbstractDoclet.startGeneration(AbstractDoclet.java:215)
	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.AbstractDoclet.run(AbstractDoclet.java:115)
	at jdk.javadoc/jdk.javadoc.doclet.StandardDoclet.run(StandardDoclet.java:103)
	at jdk.javadoc/jdk.javadoc.internal.tool.Start.parseAndExecute(Start.java:555)
	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:399)
	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:348)
	at jdk.javadoc/jdk.javadoc.internal.tool.Main.execute(Main.java:63)
	at jdk.javadoc/jdk.javadoc.internal.tool.Main.main(Main.java:52)
100 warnings
Error: Process completed with exit code 1.
```
So maybe it really is just a bug in Javadoc.

**Comment by tom-ricci** [comment]
Could be, that's why I was thinking of using Android Studio's javadoc generator instead of the original. It seemed to work for me before, I'll check if it still does.

**Comment by MatthewL246** [comment]
It's possible that the version of Javadoc in the action got auto-updated, while you still have a version that works.
```
Run ./gradlew --version

Welcome to Gradle 7.0.2!

------------------------------------------------------------
Gradle 7.0.2
------------------------------------------------------------

Build time:   2021-05-14 12:02:31 UTC
Revision:     1ef1b260d39daacbf9357f9d8594a8a743e2152e

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          16.0.2 (Eclipse Foundation 16.0.2+7)
OS:           Linux 5.11.0-1022-azure amd64
```

**Comment by tom-ricci** [comment]
Oh no its gradle 7.0.3, I think. That could be it.

**Comment by tom-ricci** [comment]
Actually I don't think it is. The Android Gradle plugin version is 7.0.3, but the Gradle version is 7.0.2

**Pull request merged**
