### PR TITLE
Release 1.0.0

### PR DESCRIPTION
**Pull request by tom-ricci**
It is time.

Well, it's not actually time yet. There's still a few things I need to do (once they're checked off I'll ping all of you again and if none of you have anything you want me to do or you want to do before this merge I'll merge it.
- [x] Debug and finish Muke's autonomous code
- [x] Implement the hand grabbing servos in both mine and Muke's code
- [ ] Debug any possible errors in my human controlled code
- [ ] Remove any debug logs from my code
- [x] Check any TODOs
- [x] Somehow keep track of control mappings
- [x] Make the second controller actually vibrate when my code is done calibrating
- [ ] Make sure everything's all good
- [ ] Draft a release
- [ ] Record 1 scrimmage run
- [x] Give you guys time to Voice Your Opinions:tm:

@XaverianTeamRobotics/xaverianrobotsteam

### CODE REVIEW

**Comment by MatthewL246** [comment]
What's the point of all the revert commits? Was that just a way to fix the merge conflicts?

**Comment by tom-ricci** [comment]
> What's the point of all the revert commits? Was that just a way to fix the merge conflicts?

No the reverts were back from when I was working on the javadoc generator and I wanted a quick way to revert back to a specific generator without having to copy and paste it

**Comment by tom-ricci** [comment]
[COLIN WHY ARE YOU CAUSING SECURITY VULNERABILITIES](https://github.com/XaverianTeamRobotics/FtcRobotController/security/code-scanning/4?query=ref%3Arefs%2Fpull%2F145%2Fmerge+ref%3Arefs%2Fpull%2F145%2Fhead+ref%3Arefs%2Fheads%2Fv1.0.0rc) /hj

**Comment by tom-ricci** [comment]
@24cteahan @MatthewL246 If you have time can you review and approve this PR?
I'm going to try to merge this with master in about an hour, so if either of you want to check this out you'll need to review it now. Michael's here and going to review this in a second, he's currently locked out of his GitHub account.

**Comment by michaell4438** [comment]
> @24cteahan @MatthewL246 If you have time can you review and approve this PR? I'm going to try to merge this with master in about an hour, so if either of you want to check this out you'll need to review it now. Michael's here and going to review this in a second, he's currently locked out of his GitHub account.

My account is now back

**Review by michaell4438 — APPROVED** [review]
5 stars out of 0

**Review by MatthewL246 — APPROVED** [review]
LGTM

**Comment by tom-ricci** [comment]
@24cteahan +1

**Comment by tom-ricci** [comment]
@24cteahan +1 (x2)

**Comment by tom-ricci** [comment]
@24cteahan +1 (FINAL WARNING)

**Comment by tom-ricci** [comment]
Merging without review

**Comment by MatthewL246** [comment]
Awesome!

:octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit:

**Pull request merged**
